name: 'Bump Version'
description: 'Generate the next version'
inputs:
  current-version:
    description: 'The current version'
    required: true
  type:
    description: 'The type of bump (major, minor, patch, run, release)'
    required: true
  commit-id:
    description: 'The commit id used for the run type'
    required: false
  is-dev:
    description: 'Whether the target version is a dev version or not (true, false)'
    required: false
    default: 'false'
outputs:
  current-version:
    description: 'The current version'
  current-branch:
    description: 'The current release branch'
  target-version:
    description: 'The generated version'
  target-branch:
    description: 'The target release branch'
  target-tag:
    description: 'The target release tag'
runs:
  using: 'node16'
  main: 'index.js'