name: Execute Maven Build
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    {}
  workflow_call:
    {}
jobs:
  build:
    name: Build Maven Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: maven
      - run: |
          VERSION=$( mvn help:evaluate -Dexpression=project.version -q -DforceStdout )
          echo "artifactVersion=$VERSION" >> $GITHUB_ENV
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - uses: actions/upload-artifact@v3
        with:
          path: client/target/java-integration-${{ env.artifactVersion }}.jar
      - uses: actions/upload-artifact@v3
        with:
          path: client/target/java-integration-${{ env.artifactVersion }}-javadoc.jar
  system-tests:
    name: Execute system-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: maven
      - uses: SAP/java-integration-for-sap-mobile-services@actions_prepare-mobile-services-app
        with:
          broker-endpoint: ${{ secrets.BROKER_ENDPOINT }}
          broker-xsuaa-client-id: ${{ secrets.BROKER_XSUAA_CLIENT_ID }}
          broker-xsuaa-url: ${{ secrets.BROKER_XSUAA_URL }}
          broker-xsuaa-cert: ${{ secrets.BROKER_XSUAA_CERT }}
          broker-xsuaa-key: ${{ secrets.BROKER_XSUAA_KEY }}
          mobile-features: 'push'
          service-key-path: ${{ github.workspace }}/validation/system-tests/service-key.json
          configurations: |
            [
              {
                "serviceName": "push",
                "x509": false,
                "scopes": [
                  "push_all",
                  "push_single"
                ],
                "configPath": "${{ github.workspace }}/validation/system-tests/service-config-api-key.json"
              }, {
                "serviceName": "push",
                "x509": true,
                "scopes": [
                  "push_all",
                  "push_single"
                ],
                "configPath": "${{ github.workspace }}/validation/system-tests/service-config-x509.json"
              }
            ]
      - env:
          SERVICE_BINDING_LOCATION: ${{ github.workspace }}/validation/system-tests/service-key.json
          SETTINGS_APIKEY_LOCATION: ${{ github.workspace }}/validation/system-tests/service-config-api-key.json
          SETTINGS_X509_LOCATION: ${{ github.workspace }}/validation/system-tests/service-config-x509.json
        run: mvn -B test --file pom.xml -pl :system-tests -Psystem-tests -DskipTests=true -am